-- Auto-generated by Antigravity using Supabase MCP Schema Extraction

CREATE TABLE arbitration_plans (
  league_id integer NOT NULL,
  name text NOT NULL,
  notes text,
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  user_id uuid NOT NULL REFERENCES users(id)
);

CREATE TABLE arbitration_allocation_details (
  league_id integer NOT NULL,
  season integer NOT NULL,
  ottoneu_id integer NOT NULL,
  player_name text NOT NULL,
  owner_team_name text,
  allocating_team_name text NOT NULL,
  amount integer NOT NULL,
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  scraped_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE player_stats (
  h1_snaps integer,
  h1_games integer,
  h2_snaps integer,
  h2_games integer,
  player_id uuid NOT NULL REFERENCES players(id),
  season integer NOT NULL,
  total_points numeric,
  games_played integer,
  snaps integer,
  ppg numeric,
  pps numeric,
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE arbitration_plan_allocations (
  plan_id uuid NOT NULL REFERENCES arbitration_plans(id),
  player_id uuid NOT NULL REFERENCES players(id),
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  amount integer DEFAULT 0 NOT NULL CHECK (amount >= 0 AND amount <= 4)
);

CREATE TABLE player_projections (
  player_id uuid NOT NULL REFERENCES players(id),
  season integer NOT NULL,
  projected_ppg numeric NOT NULL,
  projection_method text NOT NULL,
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE transactions (
  player_id uuid NOT NULL REFERENCES players(id),
  league_id integer NOT NULL,
  season integer NOT NULL,
  transaction_type text NOT NULL,
  team_name text,
  from_team text,
  salary integer,
  transaction_date date,
  raw_description text,
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  scraped_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE projection_models (
  version integer DEFAULT 1 NOT NULL,
  features jsonb DEFAULT '[]'::jsonb NOT NULL,
  name text NOT NULL,
  description text,
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  config jsonb DEFAULT '{}'::jsonb NOT NULL,
  is_baseline boolean DEFAULT false,
  is_active boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE arbitration_progress_teams (
  league_id integer NOT NULL,
  season integer NOT NULL,
  team_name text NOT NULL,
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  is_complete boolean DEFAULT false NOT NULL,
  scraped_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE users (
  email text NOT NULL UNIQUE,
  password_hash text NOT NULL,
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  is_admin boolean DEFAULT false NOT NULL,
  has_projections_access boolean DEFAULT false NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE scraper_jobs (
  task_type text NOT NULL,
  last_error text,
  batch_id uuid,
  depends_on uuid REFERENCES scraper_jobs(id),
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  params jsonb DEFAULT '{}'::jsonb NOT NULL,
  status text DEFAULT 'pending'::text NOT NULL,
  priority integer DEFAULT 0 NOT NULL,
  attempts integer DEFAULT 0 NOT NULL,
  max_attempts integer DEFAULT 3 NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE surplus_adjustments (
  player_id uuid NOT NULL REFERENCES players(id),
  league_id integer NOT NULL,
  notes text,
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  adjustment numeric DEFAULT 0 NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  user_id uuid NOT NULL REFERENCES users(id)
);

CREATE TABLE backtest_results (
  model_id uuid NOT NULL REFERENCES projection_models(id),
  season integer NOT NULL,
  position text,
  player_count integer,
  mae numeric,
  bias numeric,
  r_squared numeric,
  rmse numeric,
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE league_prices (
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  player_id uuid NOT NULL REFERENCES players(id),
  league_id integer NOT NULL,
  team_name text,
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  price integer DEFAULT 0 NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE arbitration_progress (
  league_id integer NOT NULL,
  season integer NOT NULL,
  player_name text NOT NULL,
  ottoneu_id integer,
  team_name text,
  current_salary integer,
  new_salary integer,
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  raise_amount integer DEFAULT 0 NOT NULL,
  scraped_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE nfl_stats (
  passing_attempts integer,
  completions integer,
  recent_team text,
  player_id uuid NOT NULL REFERENCES players(id),
  season integer NOT NULL,
  games_played integer,
  passing_yards integer,
  passing_tds integer,
  interceptions integer,
  rushing_yards integer,
  rushing_tds integer,
  rushing_attempts integer,
  receptions integer,
  targets integer,
  receiving_yards integer,
  receiving_tds integer,
  fg_made_0_39 integer,
  fg_made_40_49 integer,
  fg_made_50_plus integer,
  pat_made integer,
  offense_snaps integer,
  defense_snaps integer,
  st_snaps integer,
  total_snaps integer,
  total_points numeric,
  ppg numeric,
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE players (
  birth_date date,
  ottoneu_id integer NOT NULL UNIQUE,
  name text NOT NULL,
  position text,
  nfl_team text,
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  is_college boolean DEFAULT false NOT NULL
);

CREATE TABLE model_projections (
  model_id uuid NOT NULL REFERENCES projection_models(id),
  player_id uuid NOT NULL REFERENCES players(id),
  season integer NOT NULL,
  projected_ppg numeric NOT NULL,
  feature_values jsonb,
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);


-- Indexes (Copied from original schema for completeness)
create index if not exists idx_users_email on users(email);
create index if not exists idx_surplus_adjustments_league on surplus_adjustments(league_id);
create index if not exists idx_surplus_adjustments_player on surplus_adjustments(player_id);
create index if not exists idx_players_ottoneu_id on players(ottoneu_id);
create index if not exists idx_player_stats_player_id on player_stats(player_id);
create index if not exists idx_league_prices_league_id on league_prices(league_id);
create index if not exists idx_league_prices_player_id on league_prices(player_id);
create index if not exists idx_transactions_player_league on transactions(player_id, league_id, season);
create index if not exists idx_player_projections_season on player_projections(season);
create index if not exists idx_player_projections_player_id on player_projections(player_id);
create index if not exists idx_nfl_stats_season on nfl_stats(season);
create index if not exists idx_nfl_stats_player_id on nfl_stats(player_id);
create index if not exists idx_arb_progress_league_season on arbitration_progress(league_id, season);
create index if not exists idx_arb_progress_teams_league_season on arbitration_progress_teams(league_id, season);
