-- Create table for Players
create table players (
  id uuid default gen_random_uuid() primary key,
  ottoneu_id integer unique not null,
  name text not null,
  position text,
  nfl_team text,
  is_college boolean not null default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create table for Player Stats (seasonal)
create table player_stats (
  id uuid default gen_random_uuid() primary key,
  player_id uuid references players(id) not null,
  season integer not null,
  total_points numeric,
  games_played integer,
  snaps integer,
  ppg numeric,
  pps numeric,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(player_id, season)
);

-- Create table for League Prices (current state, specific to a league)
create table league_prices (
  id uuid default gen_random_uuid() primary key,
  player_id uuid references players(id) not null,
  league_id integer not null,
  price integer not null default 0,
  team_name text, -- The fantasy team that owns the player
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(player_id, league_id)
);


-- Create table for Transactions (structured event log)
create table transactions (
  id uuid default gen_random_uuid() primary key,
  player_id uuid references players(id) not null,
  league_id integer not null,
  season integer not null,
  transaction_type text not null,
  team_name text,
  from_team text,
  salary integer,
  transaction_date date,
  raw_description text,
  scraped_at timestamptz default now() not null,
  unique(player_id, league_id, transaction_type, transaction_date, salary)
);

-- Stores manual surplus value adjustments per player per league
-- Used to override VORP-calculated dollar value with scouting judgment
create table surplus_adjustments (
  id uuid default gen_random_uuid() primary key,
  player_id uuid references players(id) not null,
  league_id integer not null,
  adjustment numeric not null default 0,
  notes text,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  unique(player_id, league_id)
);

-- Stores calculated projection outputs generated by the python backend
create table player_projections (
  id uuid default gen_random_uuid() primary key,
  player_id uuid references players(id) not null,
  season integer not null,
  projected_ppg numeric not null,
  projection_method text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(player_id, season)
);

-- NFL stats: pure NFL statistical data from nflverse-data (2010-present)
-- Separate from player_stats which tracks Ottoneu fantasy data
create table nfl_stats (
  id uuid default gen_random_uuid() primary key,
  player_id uuid references players(id) not null,
  season integer not null,
  games_played integer,
  passing_yards integer,
  passing_tds integer,
  interceptions integer,
  rushing_yards integer,
  rushing_tds integer,
  rushing_attempts integer,
  receptions integer,
  targets integer,
  receiving_yards integer,
  receiving_tds integer,
  fg_made_0_39 integer,
  fg_made_40_49 integer,
  fg_made_50_plus integer,
  pat_made integer,
  offense_snaps integer,
  defense_snaps integer,
  st_snaps integer,
  total_snaps integer,
  total_points numeric,
  ppg numeric,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(player_id, season)
);

-- Create indexes for performance
create index idx_surplus_adjustments_league on surplus_adjustments(league_id);
create index idx_surplus_adjustments_player on surplus_adjustments(player_id);
create index idx_players_ottoneu_id on players(ottoneu_id);
create index idx_player_stats_player_id on player_stats(player_id);
create index idx_league_prices_league_id on league_prices(league_id);
create index idx_league_prices_player_id on league_prices(player_id);
create index idx_transactions_player_league on transactions(player_id, league_id, season);
create index idx_player_projections_season on player_projections(season);
create index idx_player_projections_player_id on player_projections(player_id);
create index idx_nfl_stats_season on nfl_stats(season);
create index idx_nfl_stats_player_id on nfl_stats(player_id);
