-- Migration 009: Add player_projections table
-- Stores projected points per game for each player and season
-- Results are generated by the backend and cached here for the frontend

CREATE TABLE IF NOT EXISTS player_projections (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  player_id uuid REFERENCES players(id) NOT NULL,
  season integer NOT NULL,
  projected_ppg numeric NOT NULL,
  projection_method text NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(player_id, season)
);

-- Index for quick lookups by season
CREATE INDEX IF NOT EXISTS idx_player_projections_season ON player_projections(season);
CREATE INDEX IF NOT EXISTS idx_player_projections_player_id ON player_projections(player_id);
