"""One-off: merge college-prospect player duplicates into their canonical row.

When a college prospect (backfilled in the offseason with a placeholder
``ottoneu_id`` and draft capital) is later drafted and rostered, Ottoneu
assigns them a *new* real ``ottoneu_id``. The roster scraper used to insert a
second ``players`` row for that real id instead of adopting the prospect
record (it only de-duped against *negative* synthetic ids — see GH #488 /
``scrape_roster.py``). The result is two rows for one human: draft capital +
projections stranded on the prospect record, while the league roster, price,
and the player page point at the new canonical record.

This script reconciles those pairs. A pair is:

  - **orphan**    — a ``players`` row that has a ``draft_capital`` row, and
  - **canonical** — a same ``(name, position)`` row that has ``transactions``
                    (i.e. it is the live, rostered record the site shows).

Requiring the canonical to have transactions scopes this to currently-rostered
players and naturally excludes the unrelated historical synthetic-id
duplicates (retired players, no transactions on either row).

For each pair it **repoints** the draft pick and any user-entered surplus
adjustments onto the canonical row, **deletes** the orphan's stale rows
(projections — regenerated by ``update_projections`` — plus the duplicate
league price, placeholder stat, and re-scrapeable draft-sharks value), then
deletes the orphan ``players`` row. Idempotent: a second run finds no pairs.

Run ``--apply`` to mutate production; the default is a dry run. Afterwards run
``just analyze`` so the canonical rows get fresh projections.
"""

from __future__ import annotations

import argparse
from typing import Dict, List, Optional

from scripts.config import get_supabase_client, fetch_all_rows


def find_pairs(supabase) -> List[Dict[str, str]]:
    """Return [{name, position, orphan_id, canon_id}] for rostered duplicates."""
    players = fetch_all_rows(supabase, "players", "id, name, position")
    by_key: Dict[tuple, List[dict]] = {}
    for p in players:
        if not p.get("name") or not p.get("position"):
            continue
        by_key.setdefault((p["name"], p["position"]), []).append(p)

    dc_ids = {r["player_id"] for r in fetch_all_rows(supabase, "draft_capital", "player_id")}
    tx_ids = {r["player_id"] for r in fetch_all_rows(supabase, "transactions", "player_id")}

    pairs: List[Dict[str, str]] = []
    for (name, position), rows in by_key.items():
        if len(rows) < 2:
            continue
        orphans = [r for r in rows if r["id"] in dc_ids and r["id"] not in tx_ids]
        canonicals = [r for r in rows if r["id"] in tx_ids]
        # Only a clean 1:1 mapping is auto-merged; ambiguous groups are skipped
        # for manual review rather than risk merging the wrong rows.
        if len(orphans) == 1 and len(canonicals) == 1:
            pairs.append({
                "name": name,
                "position": position,
                "orphan_id": orphans[0]["id"],
                "canon_id": canonicals[0]["id"],
            })
    return pairs


def _has_row(supabase, table: str, player_id: str) -> bool:
    res = supabase.table(table).select("id").eq("player_id", player_id).limit(1).execute()
    return bool(res.data)


def merge_pair(supabase, pair: Dict[str, str], apply: bool) -> List[str]:
    """Execute (or describe) the merge for one orphan→canonical pair."""
    orphan, canon = pair["orphan_id"], pair["canon_id"]
    actions: List[str] = []

    # Repoint the draft pick (draft_capital is UNIQUE on player_id; canonical
    # has none, so this never conflicts).
    actions.append("repoint draft_capital → canonical")
    if apply:
        supabase.table("draft_capital").update({"player_id": canon}).eq("player_id", orphan).execute()

    # Repoint user-entered surplus adjustments, but only if the canonical has
    # none (UNIQUE on player_id,league_id,user_id) — otherwise leave them to
    # avoid clobbering a manual value the owner already set on the canonical.
    if _has_row(supabase, "surplus_adjustments", orphan):
        if _has_row(supabase, "surplus_adjustments", canon):
            actions.append("DELETE orphan surplus_adjustments (canonical already has one)")
            if apply:
                supabase.table("surplus_adjustments").delete().eq("player_id", orphan).execute()
        else:
            actions.append("repoint surplus_adjustments → canonical")
            if apply:
                supabase.table("surplus_adjustments").update({"player_id": canon}).eq("player_id", orphan).execute()

    # Delete the orphan's stale / regenerable rows.
    for table, why in [
        ("player_projections", "regenerated by update_projections"),
        ("league_prices", "duplicate; canonical has the live price"),
        ("player_stats", "placeholder; canonical has the real row"),
        ("draft_sharks_values", "re-scrapeable"),
    ]:
        if _has_row(supabase, table, orphan):
            actions.append(f"DELETE orphan {table} ({why})")
            if apply:
                supabase.table(table).delete().eq("player_id", orphan).execute()

    actions.append("DELETE orphan players row")
    if apply:
        supabase.table("players").delete().eq("id", orphan).execute()

    return actions


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--apply", action="store_true",
                        help="Mutate production. Default is a dry run.")
    args = parser.parse_args()

    supabase = get_supabase_client()
    pairs = find_pairs(supabase)
    mode = "APPLY" if args.apply else "DRY RUN"
    print(f"[{mode}] Found {len(pairs)} duplicate pair(s) to merge.\n")
    for pair in pairs:
        print(f"• {pair['name']} ({pair['position']}): "
              f"{pair['orphan_id'][:8]} → {pair['canon_id'][:8]}")
        for action in merge_pair(supabase, pair, args.apply):
            print(f"    - {action}")
    if not args.apply and pairs:
        print("\nDry run only. Re-run with --apply to execute, then `just analyze`.")
    elif args.apply and pairs:
        print(f"\nMerged {len(pairs)} pair(s). Now run `just analyze` to "
              "regenerate projections on the canonical rows.")


if __name__ == "__main__":
    main()
